#!/usr/bin/env bash
#
# This is a small wrapper around ansible-playbook that will wait until the host is up before running
# the playbook called `server.yml` on a single server. 
# Also, it will download all dependencies that are listed on the `requirements.yml` file, if it
# exists.
#
# Usage: simple-ansible-provision [<user>@]<host> [<playbook_file>]

if [ $# -lt 1 ]; then
	echo "You must pass the host to connect!"
	echo "Usage: $0 [<user>@]<host> [<playbook_file>]"
	exit 1
fi

# The first and only parameter is always the [user@]host
if [[ "$1" =~ @ ]]; then
	user=${1%@*}
	host=${1#*@}
else
	user=
	host=$1
fi

if [ -n "$2" ]; then
	playbook="$2"
else
	playbook="server.yml"
fi

# Waits for SSH to become available
while true; do
	nc -zw 1 "$host" 22 && break || exit
	printf '.'
	sleep 1
done

# Get to where playbook is located so we look for a requirements file on the same dir.
cd "$(dirname "$playbook")" || exit 1

# Download required roles, if any
test -f requirements.yml && \
	ansible-galaxy install --ignore-errors --role-file=requirements.yml > /dev/null

# Run the playbook
ansible-playbook --inventory="$host," --user="$user" \
	--ssh-common-args="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
	"$playbook"
